/**
 * Automation Templates — Ask Magic Mike
 *
 * 20 reusable workflow template definitions.
 * All templates are pure, typed, versioned, and deterministic.
 *
 * NOTHING SENDS AUTOMATICALLY. Everything becomes "ready for broker approval."
 * Every template prepares work — humans execute.
 */

import type { WorkflowDefinition } from "./workflow-engine";

// ---------------------------------------------------------------------------
// Template registry
// ---------------------------------------------------------------------------

export const AUTOMATION_TEMPLATES: WorkflowDefinition[] = [

  // ── Lead Management ───────────────────────────────────────────────────────

  {
    id:                    "tpl_assign_followup_task",
    version:               "1.0.0",
    trigger:               "lead_created",
    name:                  "Assign Follow-up Task",
    description:           "Create a structured follow-up task for the assigned agent within 2 hours of lead creation.",
    priority:              "high",
    category:              "lead_management",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 5,
    requiresBrokerApproval: false,
    rollbackStrategy:      "Delete the created task record.",
    tags:                  ["follow-up", "task", "agent"],
    conditions:            [{ field: "newLeads24h", operator: "gt", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "assign",
        label:           "Create Follow-up Task",
        description:     "Create a priority task for the assigned agent with a 2-hour contact deadline.",
        approvalRequired: "never",
        estimatedMinutes: 2,
        rollbackCapable:  true,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "log",
        label:           "Record Assignment Event",
        description:     "Log the task creation to analytics_events for audit trail.",
        approvalRequired: "never",
        estimatedMinutes: 1,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_escalate_overdue_lead",
    version:               "1.0.0",
    trigger:               "sla_breached",
    name:                  "Escalate Overdue Lead",
    description:           "Flag leads past SLA contact window for immediate broker review and prepare reassignment options.",
    priority:              "critical",
    category:              "lead_management",
    estimatedImpact:       "critical",
    estimatedTotalMinutes: 10,
    requiresBrokerApproval: true,
    rollbackStrategy:      "Restore previous agent assignment. Remove escalation flag.",
    tags:                  ["sla", "escalation", "broker-review"],
    conditions:            [{ field: "slaBreachCount", operator: "gt", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "flag",
        label:           "Flag Lead for Escalation",
        description:     "Mark the lead record with an escalation flag for visibility.",
        approvalRequired: "never",
        estimatedMinutes: 1,
        rollbackCapable:  true,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "review",
        label:           "Broker Escalation Review",
        description:     "Prepare a broker review packet with SLA timeline and recommended next agent.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "notify_draft",
        label:           "Draft Escalation Notice",
        description:     "Prepare escalation notification draft — NOT SENT until approved.",
        approvalRequired: "always",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    ["s2"],
      },
    ],
  },

  {
    id:                    "tpl_recommend_reassignment",
    version:               "1.0.0",
    trigger:               "agent_capacity_high",
    name:                  "Recommend Reassignment",
    description:           "Identify leads assigned to over-capacity agents and prepare a reassignment proposal for broker review.",
    priority:              "high",
    category:              "agent_operations",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 15,
    requiresBrokerApproval: true,
    rollbackStrategy:      "Restore original agent assignment in lead record.",
    tags:                  ["capacity", "reassignment", "routing"],
    conditions:            [{ field: "agentCapacityPct", operator: "gte", value: 80 }],
    steps: [
      {
        id:              "s1",
        type:            "score",
        label:           "Evaluate Agent Capacity",
        description:     "Calculate current load vs. max for all active agents.",
        approvalRequired: "never",
        estimatedMinutes: 2,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Prepare Reassignment Proposal",
        description:     "Identify optimal receiving agents based on priority score and current load.",
        approvalRequired: "if_high_impact",
        estimatedMinutes: 8,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "review",
        label:           "Broker Approval for Reassignment",
        description:     "Present reassignment proposal for broker sign-off before any lead records change.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s2"],
      },
    ],
  },

  // ── Listing & Buyer Packets ───────────────────────────────────────────────

  {
    id:                    "tpl_prepare_listing_packet",
    version:               "1.0.0",
    trigger:               "listing_signed",
    name:                  "Prepare Listing Packet",
    description:           "Assemble listing checklist: seller disclosure, pricing worksheet, photography brief, listing staging prep notes.",
    priority:              "high",
    category:              "lead_management",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 20,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No data modified — packet is a document assembly, not a record change.",
    tags:                  ["listing", "packet", "checklist"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Generate Listing Checklist",
        description:     "Build the complete listing preparation checklist from the seller profile.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
        outputKeys:      ["listing_checklist"],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Prepare Photography Brief",
        description:     "Generate a property photography brief with room priority notes.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "prepare",
        label:           "Assemble Seller Disclosure Package",
        description:     "Compile required seller disclosure forms checklist for North Carolina.",
        approvalRequired: "if_high_impact",
        estimatedMinutes: 10,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_prepare_buyer_packet",
    version:               "1.0.0",
    trigger:               "buyer_agreement_signed",
    name:                  "Prepare Buyer Packet",
    description:           "Assemble buyer onboarding packet: agency agreement summary, search criteria form, financing checklist, timeline overview.",
    priority:              "high",
    category:              "lead_management",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 15,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No data modified — packet is document assembly.",
    tags:                  ["buyer", "packet", "checklist"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Generate Buyer Criteria Form",
        description:     "Compile buyer search criteria from conversation data and lead profile.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Build Financing Checklist",
        description:     "Generate pre-qualification checklist based on buyer loan readiness indicators.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "prepare",
        label:           "Assemble Timeline Overview",
        description:     "Build a buyer journey timeline: pre-qual → search → offer → close.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_prepare_cma_checklist",
    version:               "1.0.0",
    trigger:               "appointment_confirmed",
    name:                  "Prepare CMA Checklist",
    description:           "Generate a CMA preparation checklist and comparable property data pull request for the listing appointment.",
    priority:              "high",
    category:              "lead_management",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 10,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No data modified — checklist only.",
    tags:                  ["cma", "listing", "appointment"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Generate CMA Prep Checklist",
        description:     "Build a structured CMA research checklist for the assigned agent.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Flag Comparable Data Pull",
        description:     "Flag the need for comparable property data to be pulled before the appointment.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_prepare_seller_checklist",
    version:               "1.0.0",
    trigger:               "appointment_confirmed",
    name:                  "Prepare Seller Checklist",
    description:           "Generate a seller appointment prep checklist: property condition, pricing expectations, disclosure readiness.",
    priority:              "medium",
    category:              "lead_management",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 8,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No data modified.",
    tags:                  ["seller", "appointment", "checklist"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Generate Seller Prep Checklist",
        description:     "Build appointment prep checklist from seller lead profile and conversation data.",
        approvalRequired: "never",
        estimatedMinutes: 8,
        rollbackCapable:  false,
        dependencies:    [],
      },
    ],
  },

  // ── Reporting ──────────────────────────────────────────────────────────────

  {
    id:                    "tpl_generate_campaign_review",
    version:               "1.0.0",
    trigger:               "campaign_underperforming",
    name:                  "Generate Campaign Review",
    description:           "Prepare a campaign performance review with trend analysis and recommended budget reallocation options.",
    priority:              "medium",
    category:              "marketing",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 12,
    requiresBrokerApproval: true,
    rollbackStrategy:      "No campaigns modified — review document only. Reject to discard.",
    tags:                  ["campaign", "review", "marketing"],
    conditions:            [{ field: "campaignUnderperformingCount", operator: "gt", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Pull Campaign Performance Data",
        description:     "Aggregate last 30 days of campaign conversion and velocity metrics.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Generate Review Report",
        description:     "Build a structured campaign review report with trend charts and comparison benchmarks.",
        approvalRequired: "if_high_impact",
        estimatedMinutes: 7,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "review",
        label:           "Broker Review",
        description:     "Present campaign review to broker for approval before any budget action.",
        approvalRequired: "always",
        estimatedMinutes: 2,
        rollbackCapable:  false,
        dependencies:    ["s2"],
      },
    ],
  },

  {
    id:                    "tpl_morning_executive_brief",
    version:               "1.0.0",
    trigger:               "admin_review_needed",
    name:                  "Generate Executive Morning Brief",
    description:           "Assemble the daily operations briefing: overnight changes, urgent leads, campaign shifts, agent coaching flags, approval queue.",
    priority:              "high",
    category:              "reporting",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 8,
    requiresBrokerApproval: false,
    rollbackStrategy:      "Brief is read-only. No data modified.",
    tags:                  ["brief", "morning", "executive", "reporting"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Aggregate Overnight Changes",
        description:     "Compile new leads, status changes, SLA events, and campaign shifts from the last 8 hours.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Build Opportunity Summary",
        description:     "Identify highest-ROI actions available now and rank by estimated conversion impact.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "prepare",
        label:           "Compile Approval Queue",
        description:     "List all pending broker approvals sorted by urgency and estimated impact.",
        approvalRequired: "never",
        estimatedMinutes: 2,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_evening_wrap_up",
    version:               "1.0.0",
    trigger:               "admin_review_needed",
    name:                  "Generate Evening Wrap-up",
    description:           "Compile end-of-day report: leads contacted, appointments set, conversion rate for the day, tomorrow's follow-up queue.",
    priority:              "medium",
    category:              "reporting",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 6,
    requiresBrokerApproval: false,
    rollbackStrategy:      "Report is read-only. No data modified.",
    tags:                  ["wrap-up", "evening", "reporting"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Compile Day's Activity",
        description:     "Aggregate all lead contacts, status changes, and appointment events for today.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Build Tomorrow's Follow-up Queue",
        description:     "Identify all overdue and due-tomorrow follow-ups and prepare the morning action list.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_weekly_brokerage_report",
    version:               "1.0.0",
    trigger:               "admin_review_needed",
    name:                  "Generate Weekly Brokerage Report",
    description:           "Full brokerage performance summary: lead volume, conversion rates by source, agent performance, campaign ROI, week-over-week trends.",
    priority:              "medium",
    category:              "reporting",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 20,
    requiresBrokerApproval: true,
    rollbackStrategy:      "Report is read-only. No data modified.",
    tags:                  ["weekly", "brokerage", "reporting"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Pull 7-Day Lead Volume",
        description:     "Aggregate lead counts by source, type, and grade for the past 7 days.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Generate Agent Performance Summary",
        description:     "Compile per-agent conversion rates, SLA compliance, and follow-up scores.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s3",
        type:            "prepare",
        label:           "Compile Campaign ROI Analysis",
        description:     "Calculate ROI per campaign: leads generated, cost per lead, conversion rate, estimated commission value.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s4",
        type:            "prepare",
        label:           "Build Full Weekly Report",
        description:     "Assemble all sections into formatted weekly report for broker review.",
        approvalRequired: "if_high_impact",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1", "s2", "s3"],
      },
    ],
  },

  // ── Marketing ─────────────────────────────────────────────────────────────

  {
    id:                    "tpl_prepare_marketing_bundle",
    version:               "1.0.0",
    trigger:               "listing_signed",
    name:                  "Prepare Marketing Asset Bundle",
    description:           "Assemble property marketing brief: photography checklist, listing description template, social caption drafts, QR package spec, print ad dimensions.",
    priority:              "medium",
    category:              "marketing",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 15,
    requiresBrokerApproval: true,
    rollbackStrategy:      "No assets published. All are drafts. Reject to discard.",
    tags:                  ["marketing", "listing", "bundle"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Draft Listing Description",
        description:     "Generate structured listing description template with property highlights. DRAFT ONLY.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Prepare Social Caption Drafts",
        description:     "Generate 3 social post captions for the listing. NOT POSTED until approved.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "prepare",
        label:           "Assemble Print Package Spec",
        description:     "Define print ad dimensions and format requirements for flyers and postcards.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_prepare_qr_package",
    version:               "1.0.0",
    trigger:               "listing_signed",
    name:                  "Prepare QR Package",
    description:           "Define QR code tracking requirements for yard sign, flyer, and open house materials. All UTM parameters structured for attribution.",
    priority:              "low",
    category:              "marketing",
    estimatedImpact:       "low",
    estimatedTotalMinutes: 5,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No QR codes generated in production — spec document only.",
    tags:                  ["qr", "tracking", "marketing"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Build QR UTM Spec",
        description:     "Define UTM parameters (source, medium, campaign, content) for each QR placement.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
    ],
  },

  {
    id:                    "tpl_prepare_social_package",
    version:               "1.0.0",
    trigger:               "campaign_surging",
    name:                  "Prepare Social Package",
    description:           "Generate social content package for a high-performing campaign: caption variants, hashtag sets, posting schedule recommendation.",
    priority:              "medium",
    category:              "marketing",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 10,
    requiresBrokerApproval: true,
    rollbackStrategy:      "No posts published. Reject to discard draft.",
    tags:                  ["social", "content", "marketing"],
    conditions:            [{ field: "campaignSurgingCount", operator: "gt", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Draft Caption Variants",
        description:     "Generate 5 caption variants for the surging campaign. DRAFT — NOT POSTED.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Build Posting Schedule",
        description:     "Recommend optimal posting times based on historical engagement patterns.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_prepare_email_campaign",
    version:               "1.0.0",
    trigger:               "campaign_underperforming",
    name:                  "Prepare Email Campaign",
    description:           "Draft a re-engagement email campaign for leads that have gone cold. Email is NEVER sent until broker approves.",
    priority:              "medium",
    category:              "marketing",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 15,
    requiresBrokerApproval: true,
    rollbackStrategy:      "No emails sent. Draft only. Reject to discard.",
    tags:                  ["email", "campaign", "marketing"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Segment Target Audience",
        description:     "Identify leads eligible for re-engagement based on last contact date and grade.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "notify_draft",
        label:           "Draft Email Copy",
        description:     "Generate email subject line and body for broker review. DRAFT ONLY. NOT SENT.",
        approvalRequired: "always",
        estimatedMinutes: 7,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "review",
        label:           "Broker Approval",
        description:     "Email is reviewed and approved by broker before any send action is taken.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s2"],
      },
    ],
  },

  // ── Coaching ──────────────────────────────────────────────────────────────

  {
    id:                    "tpl_agent_coaching_summary",
    version:               "1.0.0",
    trigger:               "agent_capacity_low",
    name:                  "Prepare Agent Coaching Summary",
    description:           "Generate a coaching summary for an underperforming agent: SLA breach history, response rate trend, conversion gaps, and recommended focus areas.",
    priority:              "medium",
    category:              "coaching",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 12,
    requiresBrokerApproval: true,
    rollbackStrategy:      "Coaching document is read-only. No agent records modified.",
    tags:                  ["coaching", "agent", "performance"],
    conditions:            [{ field: "agentCapacityPct", operator: "lte", value: 40 }],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Compile Agent Performance Data",
        description:     "Pull conversion rate, SLA compliance, response rate, and follow-up scores for the last 30 days.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Generate Coaching Summary",
        description:     "Build a structured coaching summary with specific, actionable improvement areas.",
        approvalRequired: "if_high_impact",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "review",
        label:           "Broker Review",
        description:     "Broker reviews coaching summary before sharing with the agent.",
        approvalRequired: "always",
        estimatedMinutes: 2,
        rollbackCapable:  false,
        dependencies:    ["s2"],
      },
    ],
  },

  {
    id:                    "tpl_appointment_missed_recovery",
    version:               "1.0.0",
    trigger:               "appointment_missed",
    name:                  "Appointment Recovery Plan",
    description:           "When an appointment is missed, prepare a recovery action plan: reschedule draft, escalation flag, agent coaching note.",
    priority:              "high",
    category:              "lead_management",
    estimatedImpact:       "high",
    estimatedTotalMinutes: 10,
    requiresBrokerApproval: true,
    rollbackStrategy:      "No records modified. Recovery plan is advisory only.",
    tags:                  ["appointment", "recovery", "missed"],
    conditions:            [{ field: "appointmentsMissed24h", operator: "gt", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "flag",
        label:           "Flag Missed Appointment",
        description:     "Flag the lead record for broker visibility.",
        approvalRequired: "never",
        estimatedMinutes: 1,
        rollbackCapable:  true,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Prepare Reschedule Options",
        description:     "Build a reschedule outreach draft with 3 available time slots. DRAFT — NOT SENT.",
        approvalRequired: "always",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
      {
        id:              "s3",
        type:            "prepare",
        label:           "Generate Agent Coaching Note",
        description:     "Prepare a brief coaching note for the assigned agent regarding appointment reliability.",
        approvalRequired: "always",
        estimatedMinutes: 4,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_conversation_abandoned_recovery",
    version:               "1.0.0",
    trigger:               "conversation_abandoned",
    name:                  "Conversation Recovery",
    description:           "When a lead abandons the conversation mid-flow, prepare a re-engagement packet for agent review.",
    priority:              "medium",
    category:              "lead_management",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 8,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No data modified. Recovery packet is advisory.",
    tags:                  ["conversation", "recovery", "abandoned"],
    conditions:            [],
    steps: [
      {
        id:              "s1",
        type:            "prepare",
        label:           "Analyze Abandonment Point",
        description:     "Identify which conversation stage the lead abandoned and what signals were present.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Prepare Re-engagement Summary",
        description:     "Build a context summary for the agent to use when re-contacting the lead.",
        approvalRequired: "never",
        estimatedMinutes: 5,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_sla_warning_response",
    version:               "1.0.0",
    trigger:               "sla_warning",
    name:                  "SLA Warning Response",
    description:           "When a lead is approaching SLA contact deadline, prepare an immediate action brief for the assigned agent.",
    priority:              "critical",
    category:              "lead_management",
    estimatedImpact:       "critical",
    estimatedTotalMinutes: 3,
    requiresBrokerApproval: false,
    rollbackStrategy:      "No data modified.",
    tags:                  ["sla", "warning", "urgent"],
    conditions:            [{ field: "slaBreachCount", operator: "gte", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "flag",
        label:           "Create SLA Warning Flag",
        description:     "Mark the lead with an urgent SLA warning visible to the assigned agent.",
        approvalRequired: "never",
        estimatedMinutes: 1,
        rollbackCapable:  true,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "assign",
        label:           "Assign Urgent Task",
        description:     "Create a high-priority task for immediate agent action on this lead.",
        approvalRequired: "never",
        estimatedMinutes: 2,
        rollbackCapable:  true,
        dependencies:    ["s1"],
      },
    ],
  },

  {
    id:                    "tpl_task_overdue_escalation",
    version:               "1.0.0",
    trigger:               "task_overdue",
    name:                  "Task Overdue Escalation",
    description:           "When tasks exceed their due date, escalate to broker visibility and prepare a reassignment recommendation.",
    priority:              "high",
    category:              "agent_operations",
    estimatedImpact:       "medium",
    estimatedTotalMinutes: 5,
    requiresBrokerApproval: false,
    rollbackStrategy:      "Escalation flag can be cleared manually.",
    tags:                  ["task", "overdue", "escalation"],
    conditions:            [{ field: "overdueTasks", operator: "gt", value: 0 }],
    steps: [
      {
        id:              "s1",
        type:            "flag",
        label:           "Flag Overdue Tasks",
        description:     "Mark all overdue tasks for broker visibility in the admin dashboard.",
        approvalRequired: "never",
        estimatedMinutes: 2,
        rollbackCapable:  true,
        dependencies:    [],
      },
      {
        id:              "s2",
        type:            "prepare",
        label:           "Prepare Overdue Summary",
        description:     "Build a brief summary of overdue tasks by agent for broker coaching context.",
        approvalRequired: "never",
        estimatedMinutes: 3,
        rollbackCapable:  false,
        dependencies:    ["s1"],
      },
    ],
  },

];

// ---------------------------------------------------------------------------
// Template lookup helpers
// ---------------------------------------------------------------------------

export function getTemplate(id: string): WorkflowDefinition | undefined {
  return AUTOMATION_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(
  category: WorkflowDefinition["category"]
): WorkflowDefinition[] {
  return AUTOMATION_TEMPLATES.filter((t) => t.category === category);
}

export function getTemplatesByTrigger(
  trigger: WorkflowDefinition["trigger"]
): WorkflowDefinition[] {
  return AUTOMATION_TEMPLATES.filter((t) => t.trigger === trigger);
}

export function getTemplatesByPriority(
  priority: WorkflowDefinition["priority"]
): WorkflowDefinition[] {
  return AUTOMATION_TEMPLATES.filter((t) => t.priority === priority);
}
