export const dynamic   = "force-dynamic";
export const revalidate = 0;

import { AdminShell, AdminSectionHeading } from "@/components/admin/admin-shell";
import { AnalyticsCard, MetricGrid, MetricTile } from "@/components/admin/analytics/analytics-card";
import { InsightCard } from "@/components/admin/analytics/insight-card";
import { EmptyState } from "@/components/admin/analytics/empty-state";
import { CopyBlock } from "@/components/admin/copy-block";
import { loadDashboardMetrics } from "@/lib/admin/dashboard-metrics";
import { buildWeeklyExecutiveReport } from "@/lib/admin/weekly-executive-report";
import { loadTrafficCommand } from "@/lib/admin/traffic-command";
import {
  calculateConversion,
  calculateHealthScore,
  formatCurrency,
} from "@/lib/admin/intelligence-engine";

// ---------------------------------------------------------------------------
// Report section helper
// ---------------------------------------------------------------------------

function ReportSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <AdminSectionHeading className="mb-3">{title}</AdminSectionHeading>
      {children}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Build a formatted daily report text block
// ---------------------------------------------------------------------------

function buildDailyReport(params: {
  date: string;
  leadsToday: number;
  leadsTotal: number;
  hotCount: number;
  urgentCount: number;
  unassigned: number;
  neverContacted: number;
  appointments: number;
  bySource: Array<{ source: string; count: number }>;
}): string {
  const hotRate = params.leadsTotal > 0
    ? ((params.hotCount / params.leadsTotal) * 100).toFixed(1)
    : "0.0";
  const topSource = params.bySource[0]?.source ?? "Unknown";
  const topCount  = params.bySource[0]?.count ?? 0;

  return [
    `ASK MAGIC MIKE — DAILY BRIEF`,
    `${params.date}`,
    ``,
    `LEAD ACTIVITY`,
    `  New today:          ${params.leadsToday}`,
    `  Active in system:   ${params.leadsTotal}`,
    `  Hot (A/A+):         ${params.hotCount} (${hotRate}%)`,
    `  Urgent / SLA:       ${params.urgentCount}`,
    `  Unassigned:         ${params.unassigned}`,
    `  Never contacted:    ${params.neverContacted}`,
    `  Appointments:       ${params.appointments}`,
    ``,
    `TOP SOURCE`,
    `  ${topSource}: ${topCount} leads`,
    ``,
    `ACTION ITEMS`,
    params.urgentCount > 0
      ? `  [CRITICAL] ${params.urgentCount} SLA breach${params.urgentCount > 1 ? "es" : ""} — contact immediately`
      : `  No SLA breaches`,
    params.neverContacted > 0
      ? `  [HIGH] ${params.neverContacted} lead${params.neverContacted > 1 ? "s" : ""} never contacted`
      : `  All assigned leads have been contacted`,
    params.unassigned > 0
      ? `  [HIGH] ${params.unassigned} lead${params.unassigned > 1 ? "s" : ""} awaiting assignment`
      : `  No unassigned leads`,
    ``,
    `Generated by Ask Magic Mike · askmagicmike.com · Our Town Properties, Inc. · Wilson, NC`,
    `No data was exported. This is a read-only summary.`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default async function ExecutiveReportsPage() {
  const metrics = await loadDashboardMetrics();
  const devMode = !metrics.configured;

  const t = metrics.totals;
  const total          = metrics.recentLeads.length;
  const hotCount       = t.hot;
  const urgentCount    = t.overdueSla;
  const unassigned     = t.unassigned;
  const neverContacted = t.neverContacted;
  const appointments   = t.appointmentsRequested;
  const cashOffer      = t.sellerCashOffer;
  const listingInq     = t.listingInquiries;
  const bySource       = metrics.bySource.slice(0, 6);

  const hotRate   = calculateConversion(hotCount, total);
  const slaRate   = calculateConversion(total - urgentCount, total);

  const health = calculateHealthScore({
    conversionRate:   hotRate.rate,
    responseRate:     total > 0 ? ((total - neverContacted) / total) * 100 : 0,
    slaCompliance:    slaRate.rate,
    pipelineActivity: appointments > 0 ? 60 : 20,
    dataQuality:      80,
  });

  const now  = new Date();
  const dateLabel = now.toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const dailyReportText = buildDailyReport({
    date: dateLabel,
    leadsToday:    t.newToday,
    leadsTotal:    total,
    hotCount,
    urgentCount,
    unassigned,
    neverContacted,
    appointments,
    bySource,
  });

  return (
    <AdminShell
      title="Executive Reports"
      eyebrow="Ask Magic Mike · Analytics"
      backHref="/admin/analytics"
      backLabel="← executive"
      devMode={devMode}
      headerRight={
        <span className="text-xs text-slate-600">{dateLabel}</span>
      }
    >
      <main className="max-w-7xl mx-auto px-6 py-8 space-y-8">

        {/* ── Disclaimer ── */}
        <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-5 py-4">
          <p className="text-xs text-slate-500 leading-relaxed">
            All reports are <strong className="text-slate-300">read-only</strong> and generated locally from your existing database.
            No data is exported, emailed, or sent to any external system.
            Copy any report text and paste it into your workflow.
          </p>
        </div>

        {/* ── Daily Brief ── */}
        <AnalyticsCard title="Daily Brief" subtitle={dateLabel} accent="gold">
          <div className="space-y-4 mt-2">
            <MetricGrid cols={4}>
              <MetricTile label="Today"        value={t.newToday}  accent />
              <MetricTile label="Hot / A+"     value={hotCount}    />
              <MetricTile label="Urgent"       value={urgentCount} urgent={urgentCount > 0} />
              <MetricTile label="Appointments" value={appointments} />
            </MetricGrid>

            <CopyBlock
              label="Daily Brief — copy and paste into your notes or CRM"
              content={dailyReportText}
              mono
            />
          </div>
        </AnalyticsCard>

        {/* ── Operations Health ── */}
        <AnalyticsCard title="Operations Health Report" accent={health.grade === "A" ? "emerald" : "amber"}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-2">
            <div>
              <div className="flex items-center gap-4 mb-4">
                <div className={[
                  "h-14 w-14 rounded-full border-2 flex items-center justify-center shrink-0",
                  health.grade === "A" ? "border-emerald-400/40 bg-emerald-400/[0.06]"
                  : health.grade === "B" ? "border-gold-400/40 bg-gold-400/[0.06]"
                  : health.grade === "C" ? "border-amber-400/40 bg-amber-400/[0.06]"
                  : "border-ruby-400/40 bg-ruby-400/[0.06]",
                ].join(" ")}
                aria-label={`Health grade ${health.grade}`}
                >
                  <span className={[
                    "font-bebas text-2xl",
                    health.grade === "A" ? "text-emerald-400"
                    : health.grade === "B" ? "text-gold-300"
                    : health.grade === "C" ? "text-amber-400"
                    : "text-ruby-400",
                  ].join(" ")}>
                    {health.grade}
                  </span>
                </div>
                <div>
                  <p className="text-lg font-semibold text-cream">{health.label}</p>
                  <p className="text-xs text-slate-500">{health.score}/100 overall health</p>
                </div>
              </div>
              {health.warnings.length > 0 ? (
                <ul className="space-y-1.5" aria-label="Health warnings">
                  {health.warnings.map((w) => (
                    <li key={w} className="text-xs text-amber-400/70 flex items-start gap-1.5">
                      <span className="h-1 w-1 rounded-full bg-amber-400/50 mt-1.5 shrink-0" aria-hidden="true" />
                      {w}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-emerald-400/70">All operations within normal parameters</p>
              )}
            </div>

            <div className="space-y-2">
              {[
                { label: "Conversion Rate",   value: hotRate.label,               note: "Hot leads / total" },
                { label: "SLA Compliance",    value: slaRate.label,               note: "Within SLA window" },
                { label: "Response Coverage", value: total > 0 ? `${(((total - neverContacted) / total) * 100).toFixed(0)}%` : "—", note: "Leads with contact" },
                { label: "High Intent Leads", value: cashOffer + listingInq,      note: "Cash offer + listing" },
              ].map((row) => (
                <div key={row.label} className="flex items-center justify-between gap-3 py-1.5 border-b border-white/[0.04] last:border-0">
                  <p className="text-xs text-slate-400">{row.label}</p>
                  <div className="text-right">
                    <p className="text-sm font-mono text-cream tabular-nums">{row.value}</p>
                    <p className="text-[9px] text-slate-600">{row.note}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </AnalyticsCard>

        {/* ── Weekly summary ── */}
        <AnalyticsCard title="Weekly Pipeline Summary" accent="gold">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-2">
            <InsightCard
              title="Pipeline Leads"
              value={total}
              description="Active in system"
              status="neutral"
            />
            <InsightCard
              title="Hot Leads"
              value={hotCount}
              description={`${hotRate.label} qualification rate`}
              status={hotCount > 0 ? "positive" : "neutral"}
            />
            <InsightCard
              title="Cash Offer / Seller"
              value={cashOffer}
              description="High-intent seller signals"
              status={cashOffer > 0 ? "positive" : "neutral"}
            />
            <InsightCard
              title="Listing Inquiries"
              value={listingInq}
              description="Active listing interest"
              status={listingInq > 0 ? "positive" : "neutral"}
            />
          </div>

          <div className="mt-4">
            <CopyBlock
              label="Copy weekly pipeline summary"
              content={[
                `WEEKLY PIPELINE SUMMARY — Week of ${dateLabel}`,
                ``,
                `Pipeline: ${total} active leads`,
                `Hot (A/A+): ${hotCount} (${hotRate.label})`,
                `Cash Offer Interest: ${cashOffer}`,
                `Listing Inquiries: ${listingInq}`,
                `Appointments Requested: ${appointments}`,
                `SLA Compliance: ${slaRate.label}`,
                `Operations Health: ${health.grade} — ${health.label}`,
                ``,
                `Top Source: ${bySource[0]?.source ?? "Unknown"} (${bySource[0]?.count ?? 0} leads)`,
                ``,
                `Generated: Ask Magic Mike · Our Town Properties, Inc. · Wilson, NC`,
              ].join("\n")}
              mono
            />
          </div>
        </AnalyticsCard>

        {/* ── Source Report ── */}
        <AnalyticsCard
          title="Source Attribution Report"
          subtitle="Lead count by traffic source — current 500-lead window"
        >
          {bySource.length === 0 ? (
            <EmptyState
              title="No source data available"
              description="Source data will appear once leads arrive with UTM parameters."
              variant="data"
            />
          ) : (
            <div className="space-y-2 mt-2">
              {bySource.map((s, i) => {
                const pct = total > 0 ? ((s.count / total) * 100).toFixed(1) : "0.0";
                return (
                  <div
                    key={s.source ?? i}
                    className="flex items-center gap-4 py-2 border-b border-white/[0.04] last:border-0"
                  >
                    <span className="text-[10px] font-mono text-slate-700 w-4 shrink-0">{i + 1}</span>
                    <p className="text-xs text-slate-300 flex-1">{s.source ?? "Unknown"}</p>
                    <p className="text-sm font-mono text-cream tabular-nums w-8 text-right">{s.count}</p>
                    <p className="text-[10px] font-mono text-slate-600 w-12 text-right tabular-nums">{pct}%</p>
                  </div>
                );
              })}
            </div>
          )}
        </AnalyticsCard>

        {/* ── Report types available ── */}
        <AnalyticsCard
          title="Available Report Types"
          subtitle="All generated locally — no data leaves this system"
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-2">
            {[
              { name: "Daily Brief",              status: "available",    desc: "Today's lead activity, SLA status, urgent queue" },
              { name: "Weekly Pipeline Summary",  status: "available",    desc: "7-day totals, conversion, source breakdown" },
              { name: "Operations Health Report", status: "available",    desc: "Scoring across conversion, SLA, response, data quality" },
              { name: "Source Attribution Report",status: "available",    desc: "Lead volume by UTM source, share percentages" },
              { name: "Monthly Broker Report",    status: "coming",       desc: "Requires 30+ days of data in pipeline" },
              { name: "Campaign Performance Report",status: "coming",     desc: "Requires campaign attribution table" },
              { name: "Agent Scorecard",          status: "coming",       desc: "Requires lead routing and agent assignment tables" },
              { name: "Conversation Transcript Report", status: "coming", desc: "Requires message history storage" },
            ].map((r) => (
              <div
                key={r.name}
                className="flex items-start gap-3 py-2 border-b border-white/[0.04] last:border-0"
              >
                <span
                  className={[
                    "shrink-0 mt-0.5 text-[9px] tracking-label font-bold uppercase border rounded-full px-1.5 py-0.5",
                    r.status === "available"
                      ? "text-emerald-400 border-emerald-400/25 bg-emerald-400/[0.06]"
                      : "text-slate-600 border-white/[0.06]",
                  ].join(" ")}
                >
                  {r.status === "available" ? "Live" : "Future"}
                </span>
                <div>
                  <p className="text-xs font-semibold text-slate-300 leading-none mb-0.5">{r.name}</p>
                  <p className="text-[10px] text-slate-600 leading-snug">{r.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </AnalyticsCard>

      </main>
    </AdminShell>
  );
}
