"use client";
import { useState,useEffect } from "react";
import { ALLOCATION_CONSENT_TEXT,ALLOCATION_CONSENT_VERSION } from "../../lib/leadAllocationConsent";
type Enrollment={approved_at:string|null;possession_verified_at:string|null;consent_at:string|null;revoked_at:string|null;paused:boolean;email_enabled:boolean;sms_enabled:boolean;mms_enabled:boolean;towns:string[];intents:string[]};
export function StaffAllocationEnrollment({administrator}:{administrator:boolean}) {
 const [enrollment,setEnrollment]=useState<Enrollment|null>(null),[held,setHeld]=useState(true),[result,setResult]=useState(""),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{fetch("/api/admin/allocation/enrollment").then(r=>r.json()).then(data=>{if(data.ok){setEnrollment(data.enrollment);setHeld(data.held);}else setResult(data.error);}).catch(()=>setResult("Enrollment read unavailable."));},[]);
 async function post(body:object) {
  if(busy)return;setBusy(true);setResult("");
  try{const response=await fetch("/api/admin/allocation/enrollment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setResult(data.ok?(data.command?`Private possession challenge: ${data.command}. ${data.notice}`:"Change committed. Refresh your current enrollment; no outbound message was sent."):`Held: ${data.error||"binding or approval required"}.`);}
  catch{setResult("Outcome unconfirmed. Inspect enrollment before retrying.");}finally{setBusy(false);}
 }
 const disabled=held||busy;
 return <section className="rounded-2xl border border-[#D9AF52]/40 bg-[#121619] p-5 text-[#F5EAD1]">
  <h2 className="text-xl font-semibold">Operational channel enrollment</h2><p className="mt-3 text-sm leading-6">Approved roster binding first. Possession and operational consent are separate. RESUME only changes availability; it never revives revoked consent. Existing directory destinations remain server-side.</p>
  <p className="my-4 text-sm text-[#D9AF52]">{held?"Activation held; no enrollment change or paid traffic.":enrollment?"Approved binding found. Review current status below.":"No approved binding. Administrator review required."}</p>
  {enrollment?<dl className="my-4 grid gap-3 sm:grid-cols-2">{Object.entries({Approval:enrollment.approved_at?"Recorded":"Missing",Possession:enrollment.possession_verified_at?"Verified":"Not verified",Consent:enrollment.consent_at?"Recorded":"Missing",Availability:enrollment.revoked_at?"Revoked":enrollment.paused?"Paused":"Available",Coverage:enrollment.towns.join(", ")||"None",Intents:enrollment.intents.join(", ")||"None"}).map(([k,v])=><div key={k}><dt className="text-xs text-[#D9AF52]">{k}</dt><dd className="mt-1 text-sm">{v}</dd></div>)}</dl>:null}
  <fieldset disabled={disabled} className="space-y-4"><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 h-5 w-5"/>{ALLOCATION_CONSENT_TEXT}</label>
   <div className="flex flex-wrap gap-3">{[["consent","Record operational consent"],["challenge","Prepare possession challenge"],["pause","Pause allocation"],["resume","Resume availability"],["revoke","Revoke enrollment"]].map(([action,label])=><button key={action} disabled={disabled||(action==="consent"&&!confirmed)} onClick={()=>post(action==="consent"?{action,text:ALLOCATION_CONSENT_TEXT,version:ALLOCATION_CONSENT_VERSION,confirmed:true}:{action})} className="min-h-11 rounded-lg border border-[#D9AF52]/40 px-4 py-3 text-sm disabled:opacity-50">{label}</button>)}</div>
   <form action={form=>post({action:"preferences",email:form.get("email")==="on",sms:form.get("sms")==="on",mms:form.get("mms")==="on"})} className="rounded-xl border border-[#D9AF52]/25 p-4"><h3 className="text-sm font-bold">Channel preferences</h3><div className="my-3 flex flex-wrap gap-4">{["email","sms","mms"].map(channel=><label key={channel} className="flex min-h-11 items-center gap-2 text-sm"><input name={channel} type="checkbox" defaultChecked={enrollment?.[`${channel}_enabled` as keyof Enrollment]===true}/>{channel.toUpperCase()}</label>)}</div><button className="min-h-11 rounded-lg bg-[#D9AF52] px-4 text-sm font-bold text-black">Save preferences · no send</button></form>
  </fieldset>
  {administrator?<form action={form=>post({action:"approve",agentId:form.get("agent"),userId:form.get("user"),towns:form.getAll("town"),intents:form.getAll("intent")})} className="mt-6 border-t border-[#D9AF52]/30 pt-5"><h3 className="font-semibold">Explicit roster binding · administrator only</h3><p className="mt-2 text-xs leading-5">Use verified existing agent/user identities. This does not approve the live routing policy or enable channels. Towns are candidates, not implied coverage.</p><fieldset disabled={disabled} className="mt-4 grid gap-3"><label className="text-sm">Existing agent ID<input name="agent" required className="mt-1 min-h-11 w-full rounded border border-[#D9AF52]/30 bg-black p-3"/></label><label className="text-sm">Bound existing user ID<input name="user" required className="mt-1 min-h-11 w-full rounded border border-[#D9AF52]/30 bg-black p-3"/></label><div className="flex flex-wrap gap-3">{["Wilson","Elm City","Lucama","Stantonsburg","Sims","Kenly"].map(town=><label key={town} className="flex min-h-11 items-center gap-2 text-sm"><input name="town" value={town} type="checkbox"/>{town}</label>)}</div><div className="flex flex-wrap gap-3">{["buyer","seller","seller_cash_offer","investor","home_value","renter"].map(intent=><label key={intent} className="flex min-h-11 items-center gap-2 text-sm"><input name="intent" value={intent} type="checkbox"/>{intent}</label>)}</div><button className="min-h-11 rounded-lg border border-[#D9AF52]/40 px-4 text-sm">Record reviewed binding · channels remain off</button></fieldset></form>:null}
  {result?<p role="status" className="mt-5 break-words text-sm">{result}</p>:null}
 </section>;
}
